stages:
  data_ingestion:
    cmd: python src\MonkeypoxClassifier\pipeline\stage_01_data_ingestion.py
    deps:
      - src\MonkeypoxClassifier\pipeline\stage_01_data_ingestion.py
      - config\config.yaml
    outs:
      - artifacts\data_ingestion\Monkey Pox Image

  prepare_base_model:
    cmd: python src\MonkeypoxClassifier\pipeline\stage_02_prepare_base_model.py
    deps:
      - src\MonkeypoxClassifier\pipeline\stage_02_prepare_base_model.py
      - src\MonkeypoxClassifier\components\prepare_base_model.py
      - config\config.yaml
      - params.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts\prepare_base_model

  training:
    cmd: python src\MonkeypoxClassifier\pipeline\stage_03_training.py
    deps:
      - src\MonkeypoxClassifier\pipeline\stage_03_training.py
      - src\MonkeypoxClassifier\components\prepare_callbacks.py
      - config\config.yaml
      - artifacts\data_ingestion\Monkey Pox Image
      - artifacts\prepare_base_model
      - params.yaml
      - src\MonkeypoxClassifier\components\training.py
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts\training\model.h5

  Evalutation:
    cmd: python src\MonkeypoxClassifier\pipeline\stage_04_evaluation.py
    deps:
      - src\MonkeypoxClassifier\pipeline\stage_04_evaluation.py
      - config\config.yaml
      - artifacts\data_ingestion\Monkey Pox Image
      - artifacts\training\model.h5
    params:
      - BATCH_SIZE
      - IMAGE_SIZE
    metrics:
      - scores.json:
          cache: False
